server:
  port: 2333

spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
      database: jobmaster
      uri: mongodb+srv://anda:123@cluster0-f4nnl.mongodb.net/test?retryWrites=true&w=majority


jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "