server:
  port: 2333

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: jobmaster

jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "